
package Principal;
import java.util.ArrayList;
import java.util.List;
/**
 *
 * @author sabri
 */
public class MenuPrincipal extends javax.swing.JFrame {
    private EstoqueProduto listaProduto;
    private GerenciarNotasFiscais listaF;
    /**
     * Construtor
     */
    public MenuPrincipal(EstoqueProduto listaProduto, GerenciarNotasFiscais listF) {
        initComponents();
        this.listaProduto=listaProduto;
        this.listaF = listF;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jColorChooser1 = new javax.swing.JColorChooser();
        TextoMenu = new javax.swing.JLabel();
        NomeGrupo = new javax.swing.JLabel();
        FotoFruteira = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        ProdutoMenu = new javax.swing.JMenu();
        GerenciarProdutoMenu = new javax.swing.JMenuItem();
        NotalFiscalMenu = new javax.swing.JMenu();
        NotaFiscal = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("FRUTEIRA");
        setPreferredSize(new java.awt.Dimension(501, 339));

        TextoMenu.setFont(new java.awt.Font("Tempus Sans ITC", 1, 40)); // NOI18N
        TextoMenu.setText("FRUTEIRA");

        NomeGrupo.setFont(new java.awt.Font("Segoe Print", 0, 10)); // NOI18N
        NomeGrupo.setForeground(new java.awt.Color(102, 102, 0));
        NomeGrupo.setText("Danielly, João, Milena e Sabrina");

        ProdutoMenu.setText("Produto");
        ProdutoMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProdutoMenuActionPerformed(evt);
            }
        });

        GerenciarProdutoMenu.setText("Gerenciar Produtos");
        GerenciarProdutoMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GerenciarProdutoMenuActionPerformed(evt);
            }
        });
        ProdutoMenu.add(GerenciarProdutoMenu);

        jMenuBar1.add(ProdutoMenu);

        NotalFiscalMenu.setText("Nota Fiscal");

        NotaFiscal.setText("Notas Fiscais");
        NotaFiscal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NotaFiscalActionPerformed(evt);
            }
        });
        NotalFiscalMenu.add(NotaFiscal);

        jMenuBar1.add(NotalFiscalMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(TextoMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(FotoFruteira, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(125, 125, 125))
            .addGroup(layout.createSequentialGroup()
                .addGap(305, 305, 305)
                .addComponent(NomeGrupo)
                .addContainerGap(186, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(FotoFruteira))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(TextoMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 162, Short.MAX_VALUE)
                .addComponent(NomeGrupo))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ProdutoMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProdutoMenuActionPerformed
   
    }//GEN-LAST:event_ProdutoMenuActionPerformed

    
    
    //ABRE A TELA DE CADASTRAR PRODUTOS
    private void GerenciarProdutoMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GerenciarProdutoMenuActionPerformed
        // TODO add your handling code here:
        InterfaceProduto interfaceProduto = new InterfaceProduto(listaProduto);
        interfaceProduto.setVisible(true);
    }//GEN-LAST:event_GerenciarProdutoMenuActionPerformed
  
    
    //ABRE A TELA DA NOTA FISCAL
    private void NotaFiscalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NotaFiscalActionPerformed
       InterfaceNotasFiscais interfaceNotasFiscais = new InterfaceNotasFiscais(listaF);
       interfaceNotasFiscais.setVisible(true);
    }//GEN-LAST:event_NotaFiscalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ArrayList<Produto> produto = new ArrayList<>();
                ArrayList<NotaFiscal> listaF = new ArrayList<>();
                new MenuPrincipal(new EstoqueProduto(produto), new GerenciarNotasFiscais(listaF)).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FotoFruteira;
    private javax.swing.JMenuItem GerenciarProdutoMenu;
    private javax.swing.JLabel NomeGrupo;
    private javax.swing.JMenuItem NotaFiscal;
    private javax.swing.JMenu NotalFiscalMenu;
    private javax.swing.JMenu ProdutoMenu;
    private javax.swing.JLabel TextoMenu;
    private javax.swing.JColorChooser jColorChooser1;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}



